version: '3'

services:
  veo-studio:
    image: peanutchou/gemini-banana-veo-service:latest
    container_name: veo-studio
    restart: always
    ports:
      - "3000:3000"
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
